import type { ClinicalDraft } from '../../types/models'
import { Card } from '../ui/Card'
import { TextArea } from '../ui/Field'

type Props={draft:ClinicalDraft;onChange:(next:ClinicalDraft)=>void;readOnly?:boolean}
export function ClinicalNoteEditor({draft,onChange,readOnly=false}:Props){
 const set=(section:'subjective'|'objective'|'assessment'|'plan',field:string,value:unknown)=>onChange({...draft,[section]:{...draft[section],[field]:value}} as ClinicalDraft)
 return <div className="space-y-4">
  <Card className="p-5"><h3 className="mb-4 text-lg font-bold">Subjective</h3><div className="grid gap-4"><TextArea disabled={readOnly} label="Presenting complaint" value={draft.subjective.presenting_complaint} onChange={e=>set('subjective','presenting_complaint',e.target.value)}/><TextArea disabled={readOnly} label="History" value={draft.subjective.history} onChange={e=>set('subjective','history',e.target.value)}/><TextArea disabled={readOnly} label="Owner observations" value={draft.subjective.owner_observations} onChange={e=>set('subjective','owner_observations',e.target.value)}/></div></Card>
  <Card className="p-5"><h3 className="mb-4 text-lg font-bold">Objective</h3><div className="grid gap-4"><TextArea disabled={readOnly} label="Clinical findings" value={draft.objective.clinical_findings} onChange={e=>set('objective','clinical_findings',e.target.value)}/><TextArea disabled={readOnly} label="Vital parameters" value={draft.objective.vital_parameters.map(v=>`${v.name}: ${v.value}`).join('\n')} onChange={e=>set('objective','vital_parameters',e.target.value.split('\n').filter(Boolean).map(line=>{const [name,...rest]=line.split(':');return {name:name.trim(),value:rest.join(':').trim()}}))}/><TextArea disabled={readOnly} label="Diagnostic tests" value={draft.objective.diagnostic_tests.map(t=>`${t.test} — ${t.status}${t.result?` — ${t.result}`:''}`).join('\n')} onChange={e=>set('objective','diagnostic_tests',e.target.value.split('\n').filter(Boolean).map(line=>({test:line,status:'discussed' as const,result:null})))}/></div></Card>
  <Card className="p-5"><h3 className="mb-4 text-lg font-bold">Assessment</h3><div className="grid gap-4"><TextArea disabled={readOnly} label="Primary assessment" value={draft.assessment.primary_assessment} onChange={e=>set('assessment','primary_assessment',e.target.value)}/><TextArea disabled={readOnly} label="Diagnoses (one per line)" value={draft.assessment.diagnoses.join('\n')} onChange={e=>set('assessment','diagnoses',e.target.value.split('\n').filter(Boolean))}/><TextArea disabled={readOnly} label="Differentials (one per line)" value={draft.assessment.differentials.join('\n')} onChange={e=>set('assessment','differentials',e.target.value.split('\n').filter(Boolean))}/></div></Card>
  <Card className="p-5"><h3 className="mb-4 text-lg font-bold">Plan</h3><div className="grid gap-4"><TextArea disabled={readOnly} label="Treatment" value={draft.plan.treatment_given.join('\n')} onChange={e=>set('plan','treatment_given',e.target.value.split('\n').filter(Boolean))}/><TextArea disabled={readOnly} label="Medications" value={draft.plan.medications.map(m=>[m.name,m.dose,m.route,m.frequency,m.duration].filter(Boolean).join(' · ')).join('\n')} onChange={e=>set('plan','medications',e.target.value.split('\n').filter(Boolean).map(name=>({name,dose:null,route:null,frequency:null,duration:null})))}/><TextArea disabled={readOnly} label="Follow-up" value={draft.plan.follow_up} onChange={e=>set('plan','follow_up',e.target.value)}/><TextArea disabled={readOnly} label="Client advice" value={draft.plan.client_advice} onChange={e=>set('plan','client_advice',e.target.value)}/></div></Card>
 </div>
}
