import { jsPDF } from 'jspdf'
import type { ClinicalDraft, OwnerSummary } from '../../types/models'

function addWrapped(doc:jsPDF,text:string,x:number,y:number,maxWidth=170){ const lines=doc.splitTextToSize(text||'—',maxWidth); doc.text(lines,x,y); return y+(lines.length*5.5) }
export function exportClinicalRecordPdf(args:{practiceName:string;patientName:string;clientName:string;date:string;vetName:string;note:ClinicalDraft;approvedBy:string;version:number}){
 const doc=new jsPDF(); let y=18; doc.setFontSize(18); doc.text(args.practiceName,20,y); y+=10; doc.setFontSize(13); doc.text('Clinical Record',20,y); y+=9; doc.setFontSize(10); y=addWrapped(doc,`Patient: ${args.patientName} | Client: ${args.clientName} | Consultation: ${args.date} | Treating veterinary surgeon: ${args.vetName}`,20,y); y+=4;
 const sections:[string,string][]=[['Subjective',`${args.note.subjective.presenting_complaint}\n${args.note.subjective.history}\n${args.note.subjective.owner_observations}`],['Objective',`${args.note.objective.clinical_findings}\n${args.note.objective.vital_parameters.map(v=>`${v.name}: ${v.value}`).join('; ')}`],['Assessment',`${args.note.assessment.primary_assessment}\nDifferentials: ${args.note.assessment.differentials.join(', ')||'—'}`],['Plan',`${args.note.plan.treatment_given.join('; ')}\n${args.note.plan.client_advice}\nFollow-up: ${args.note.plan.follow_up}`]];
 for(const [title,body] of sections){ if(y>260){doc.addPage();y=18} doc.setFontSize(12); doc.setFont('helvetica','bold'); doc.text(title,20,y); y+=6; doc.setFont('helvetica','normal'); doc.setFontSize(10); y=addWrapped(doc,body,20,y); y+=5 }
 if(y>250){doc.addPage();y=18} doc.setFontSize(9); doc.text(`Approved by ${args.approvedBy} · Version ${args.version}`,20,y); doc.save(`${args.patientName}-clinical-record.pdf`)
}
export function exportOwnerSummaryPdf(practiceName:string, summary:OwnerSummary){ const doc=new jsPDF(); let y=18; doc.setFontSize(18); doc.text(practiceName,20,y); y+=10; doc.setFontSize(14); doc.text(summary.title,20,y); y+=10; const sections:[string,string][]=[['What we found',summary.whatWeFound],['What we discussed',summary.whatWeDiscussed],['Treatment and medication',summary.treatmentAndMedication],['What to do at home',summary.whatToDoAtHome],['When to contact us',summary.whenToContactUs],['Follow-up',summary.followUp]]; for(const [t,b] of sections){ doc.setFont('helvetica','bold'); doc.setFontSize(11); doc.text(t,20,y); y+=6; doc.setFont('helvetica','normal'); doc.setFontSize(10); y=addWrapped(doc,b,20,y); y+=6; if(y>270){doc.addPage();y=18} } doc.save(`${summary.title.replace(/\s+/g,'-').toLowerCase()}.pdf`) }
