import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom'
import type { ReactNode } from 'react'
import type { Role } from './types/models'
import { AppShell } from './components/layout/AppShell'
import { useAppState } from './lib/AppState'
import { LoginPage } from './pages/LoginPage'
import { ForgotPasswordPage } from './pages/ForgotPasswordPage'
import { DashboardPage } from './pages/DashboardPage'
import { ConsultationsPage } from './pages/ConsultationsPage'
import { NewConsultationPage } from './pages/NewConsultationPage'
import { ConsultationDetailPage } from './pages/ConsultationDetailPage'
import { PatientsPage } from './pages/PatientsPage'
import { PatientDetailPage } from './pages/PatientDetailPage'
import { ClientsPage } from './pages/ClientsPage'
import { ClientDetailPage } from './pages/ClientDetailPage'
import { OwnerSummariesPage } from './pages/OwnerSummariesPage'
import { SettingsPage } from './pages/SettingsPage'
import { PracticeSettingsPage } from './pages/PracticeSettingsPage'
import { StaffPage } from './pages/StaffPage'
import { TemplatesPage } from './pages/TemplatesPage'
import { PrivacyPage } from './pages/PrivacyPage'
import { AuditPage } from './pages/AuditPage'
import { AdminPage } from './pages/AdminPage'
import { NotFoundPage } from './pages/NotFoundPage'

function Protected({children}:{children:ReactNode}){const {currentUser}=useAppState();return currentUser?<>{children}</>:<Navigate to="/login" replace/>}
function RoleGate({allowed,children}:{allowed:Role[];children:ReactNode}){const {currentUser}=useAppState();return currentUser&&allowed.includes(currentUser.role)?<>{children}</>:<Navigate to="/dashboard" replace/>}
export function App(){return <BrowserRouter><Routes><Route path="/login" element={<LoginPage/>}/><Route path="/forgot-password" element={<ForgotPasswordPage/>}/><Route element={<Protected><AppShell/></Protected>}><Route index element={<Navigate to="/dashboard" replace/>}/><Route path="/dashboard" element={<DashboardPage/>}/><Route path="/consultations" element={<ConsultationsPage/>}/><Route path="/consultations/new" element={<NewConsultationPage/>}/><Route path="/consultations/:id" element={<ConsultationDetailPage/>}/><Route path="/patients" element={<PatientsPage/>}/><Route path="/patients/:id" element={<PatientDetailPage/>}/><Route path="/clients" element={<ClientsPage/>}/><Route path="/clients/:id" element={<ClientDetailPage/>}/><Route path="/owner-summaries" element={<OwnerSummariesPage/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="/settings/practice" element={<RoleGate allowed={['practice_manager']}><PracticeSettingsPage/></RoleGate>}/><Route path="/settings/staff" element={<RoleGate allowed={['practice_manager']}><StaffPage/></RoleGate>}/><Route path="/settings/templates" element={<RoleGate allowed={['practice_manager']}><TemplatesPage/></RoleGate>}/><Route path="/settings/privacy" element={<RoleGate allowed={['practice_manager']}><PrivacyPage/></RoleGate>}/><Route path="/settings/audit" element={<RoleGate allowed={['practice_manager']}><AuditPage/></RoleGate>}/><Route path="/admin" element={<RoleGate allowed={['super_admin']}><AdminPage/></RoleGate>}/><Route path="/admin/practices" element={<RoleGate allowed={['super_admin']}><AdminPage/></RoleGate>}/><Route path="/admin/practices/:id" element={<RoleGate allowed={['super_admin']}><AdminPage/></RoleGate>}/><Route path="*" element={<NotFoundPage/>}/></Route></Routes></BrowserRouter>}
