import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Plus, Search } from 'lucide-react'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { StatusBadge } from '../components/ui/Badge'
import { useAppState } from '../lib/AppState'
import { formatDateTime, fullName } from '../lib/format'
export function ConsultationsPage(){const {consultations,patients,clients,profiles}=useAppState();const [tab,setTab]=useState('all');const [q,setQ]=useState('');const rows=useMemo(()=>consultations.filter(c=>{if(tab==='draft'&&c.status!=='draft')return false;if(tab==='awaiting_review'&&c.status!=='awaiting_review')return false;if(tab==='approved'&&c.status!=='approved')return false;const p=patients.find(x=>x.id===c.patientId);const cl=clients.find(x=>x.id===c.clientId);return `${p?.name} ${cl?.firstName} ${cl?.lastName} ${c.consultationDate}`.toLowerCase().includes(q.toLowerCase())}),[consultations,patients,clients,tab,q]);return <div className="space-y-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">Consultations</h2><p className="text-sm text-slate-500">Review drafts, approved records and active work.</p></div><Link to="/consultations/new"><Button><Plus size={17}/>New Consultation</Button></Link></div><Card><div className="flex flex-wrap gap-2 border-b p-4">{['all','draft','awaiting_review','approved'].map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-lg px-3 py-2 text-sm font-semibold ${tab===t?'bg-brand-50 text-brand-800':'text-slate-500 hover:bg-slate-50'}`}>{t.replace('_',' ')}</button>)}<div className="relative ml-auto min-w-60"><Search className="absolute left-3 top-2.5 text-slate-400" size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search patient, client or date" className="w-full rounded-lg border border-slate-300 py-2 pl-9 pr-3 text-sm"/></div></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Patient','Owner','Date/time','Vet','Status','Last updated',''].map((x,i)=><th className="px-5 py-3" key={i}>{x}</th>)}</tr></thead><tbody>{rows.map(c=>{const p=patients.find(x=>x.id===c.patientId)!;const cl=clients.find(x=>x.id===c.clientId)!;const vet=profiles.find(x=>x.id===c.treatingVetId)!;return <tr className="border-t" key={c.id}><td className="px-5 py-4 font-semibold">{p.name}</td><td className="px-5 py-4">{fullName(cl)}</td><td className="px-5 py-4">{formatDateTime(c.consultationDate)}</td><td className="px-5 py-4">{fullName(vet)}</td><td className="px-5 py-4"><StatusBadge status={c.status}/></td><td className="px-5 py-4 text-slate-500">{formatDateTime(c.updatedAt)}</td><td className="px-5 py-4"><Link className="font-semibold text-brand-700" to={`/consultations/${c.id}`}>Open</Link></td></tr>})}</tbody></table>{rows.length===0&&<div className="p-10 text-center text-sm text-slate-500">No consultations match this view.</div>}</div></Card></div>}
