import { Link } from 'react-router-dom'
import { ArrowRight, Clock3, FileCheck2, FileClock, Plus } from 'lucide-react'
import { Card } from '../components/ui/Card'
import { Button } from '../components/ui/Button'
import { StatusBadge } from '../components/ui/Badge'
import { useAppState } from '../lib/AppState'
import { formatTime, fullName } from '../lib/format'
export function DashboardPage(){ const {currentUser,practice,consultations,patients,clients,profiles}=useAppState(); const approved=consultations.filter(c=>c.status==='approved').length; const drafts=consultations.filter(c=>c.status!=='approved').length; const metrics=[['Today\'s Consultations',consultations.length,Clock3],['Draft Notes',drafts,FileClock],['Completed Notes',approved,FileCheck2],['Estimated Time Saved','1h 24m',Clock3]] as const;
 return <div className="space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-3xl font-bold tracking-tight">Good morning, {currentUser?.firstName}</h2><p className="mt-1 text-slate-600">Here's what's happening at {practice.name} today.</p></div><Link to="/consultations/new"><Button><Plus size={17}/>New Consultation</Button></Link></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,Icon],i)=><Card key={label} className="p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p>{i===3&&<p className="mt-1 text-xs text-slate-400">Demo metric</p>}</div><span className="rounded-lg bg-brand-50 p-2 text-brand-700"><Icon size={20}/></span></div></Card>)}</div><Card><div className="flex items-center justify-between border-b px-5 py-4"><div><h3 className="font-semibold">Today's consultations</h3><p className="text-sm text-slate-500">Fictional demo schedule</p></div><Link to="/consultations" className="text-sm font-semibold text-brand-700">View all</Link></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{['Time','Patient','Owner','Vet','Status','Action'].map(h=><th key={h} className="px-5 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{consultations.map(c=>{const p=patients.find(x=>x.id===c.patientId)!;const cl=clients.find(x=>x.id===c.clientId)!;const vet=profiles.find(x=>x.id===c.treatingVetId)!;return <tr key={c.id} className="border-t"><td className="px-5 py-4">{formatTime(c.consultationDate)}</td><td className="px-5 py-4 font-semibold">{p.name}</td><td className="px-5 py-4">{fullName(cl)}</td><td className="px-5 py-4">{fullName(vet)}</td><td className="px-5 py-4"><StatusBadge status={c.status}/></td><td className="px-5 py-4"><Link to={`/consultations/${c.id}`} className="inline-flex items-center gap-1 font-semibold text-brand-700">Open<ArrowRight size={15}/></Link></td></tr>})}</tbody></table></div></Card></div> }
