import { useState, type FormEvent } from 'react'
import { Navigate, Link } from 'react-router-dom'
import { HeartPulse, LockKeyhole } from 'lucide-react'
import { Button } from '../components/ui/Button'
import { Field } from '../components/ui/Field'
import { Card } from '../components/ui/Card'
import { useAppState } from '../lib/AppState'
import { isSupabaseConfigured, supabase } from '../lib/supabase/client'

export function LoginPage(){ const {currentUser,loginDemo,loginProduction}=useAppState(); const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false); if(currentUser)return <Navigate to="/dashboard" replace/>;
 async function submit(e:FormEvent){e.preventDefault();setError('');if(!supabase){setError('Supabase is not configured. Use Demo Mode or add environment variables.');return} setLoading(true);const {error}=await supabase.auth.signInWithPassword({email,password});setLoading(false);if(error)setError(error.message);else {try{await loginProduction()}catch(e){setError(e instanceof Error?e.message:'Could not load practice membership')}}}
 return <div className="grid min-h-screen place-items-center bg-slate-50 p-4"><Card className="w-full max-w-md p-7"><div className="mb-7"><div className="flex items-center gap-2 text-2xl font-bold"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-700 text-white"><HeartPulse/></span>VetScribe</div><h1 className="mt-6 text-2xl font-bold">Sign in to your practice</h1><p className="mt-2 text-sm text-slate-500">Clinical documentation for independent UK veterinary practices.</p></div><form onSubmit={submit} className="space-y-4"><Field label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/><Field label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/>{error&&<div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<Button className="w-full" disabled={loading}>{loading?'Signing in…':'Sign in'}</Button></form><div className="mt-3 text-center"><Link to="/forgot-password" className="text-sm text-brand-700 hover:underline">Forgot password?</Link></div><div className="my-6 flex items-center gap-3 text-xs text-slate-400"><div className="h-px flex-1 bg-slate-200"/>DEMO<div className="h-px flex-1 bg-slate-200"/></div><Button variant="secondary" className="w-full" onClick={loginDemo}><LockKeyhole size={17}/>Use demo practice</Button><p className="mt-4 text-xs leading-5 text-slate-500">Demo data is fictional. VetScribe is a documentation assistant; veterinary professionals remain responsible for reviewing and approving clinical records.</p><p className="mt-2 text-[11px] text-slate-400">Supabase configured: {isSupabaseConfigured?'Yes':'No — demo still works'}</p></Card></div> }
